
environment:
  matrix:
    - image: Visual Studio 2017
      MINICONDA: C:\Miniconda36-x64


init:
  - "ECHO %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install anaconda-client conda-build
  - yes | anaconda login --username %CONDA_LOGIN_USERNAME% --password %CONDA_LOGIN_PASSWORD% --hostname MultiNEAT-APPVYR-WIN-BUILD-%APPVEYOR_BUILD_NUMBER%
  - conda config --set anaconda_upload %CONDA_UPLOAD%

build: false

test_script:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda build conda/ -c defaults -c conda-forge
